Added new methods as per gtmetrix api update
entrecore/php-gtmetrix pull request #8
Opened 2017-05-05 10:32 UTC by philcook

Added new methods of get and set to allow for new api timings added by gtmetrix on February 8th, 2017. Ref: https://gtmetrix.com/api/#api-changelog

2017-05-05 11:06 UTC, janoszen commented
Hello @philcook thank you for this update. The code is looking good, I will test and merge it soon.

2017-09-18 12:05 UTC, mklepaczewski commented
Any update on this?

2017-09-21 19:42 UTC, janoszen commented
Hello @mklepaczewski , unfortunately we moved away from using gtmetrix from PHP, and from PHP in general, and we will no longer be able to maintain this version of the client. I will mark the copy as abandoned in composer.

2017-09-21 19:46 UTC, philcook commented
@janoszen I would be happy to take over this project

2017-09-21 22:38 UTC, mklepaczewski requested changes
getRumSpeedIndex() returns $this->pageElements instead of $this->rumSpeedIndex

2017-09-21 22:40 UTC, mklepaczewski commented
I would be happy to chip in some hours to support the project as well.

2017-09-22 17:11 UTC, philcook commented
@mklepaczewski thanks for the spot there updated my pull request. If we don't get any movement on taking over the project I will just fork it and then submit it again to composer.

2017-09-26 16:52 UTC, ghost commented
@philcook can you send me the Packagist package name of your fork? I marked ours as abandoned, but I'm happy to add yours as the "official" alternative.

2017-09-28 11:04 UTC, philcook commented
@janoszen I have setup and submitted my fork to packagist it's now here.
https://packagist.org/packages/philcook/gtmetrix

2017-09-28 11:54 UTC, janoszen commented
@philcook I have updated packagist and the README.md to point to your fork, and I'm closing this pull request. Thanks for continuing development.

2017-09-28 11:54 UTC, closed without merging